---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - batch.example.com
  resources:
  - podgroups
  - queues
  - trainjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.example.com
  resources:
  - queues/finalizers
  - trainjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.example.com
  resources:
  - queues/status
  - trainjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
